### ISSUE TITLE
debug plugin does not accept -p option

### ISSUE THREAD

**Issue by tbeckham** [eucalyptus/calyptos#15]
The debug plugin will not accept the -p option thus you cannot automate password injection.

Not using password parameter:

```
[root@d-34 calyptos]# ./bin/calyptos -e environment.yml debug
Enter the SSH password for hosts in the deployment:
```

using -p

```
[root@d-34 calyptos]# ./bin/calyptos -e environment.yml -p foobar debug
Traceback (most recent call last):
  File "./bin/calyptos", line 172, in <module>
    cli(obj={})
  File "/usr/lib/python2.6/site-packages/click-4.0-py2.6.egg/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/click-4.0-py2.6.egg/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.6/site-packages/click-4.0-py2.6.egg/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.6/site-packages/click-4.0-py2.6.egg/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.6/site-packages/click-4.0-py2.6.egg/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
TypeError: debug() takes exactly 1 argument (0 given)
```

**Comment by dmccue** [comment]
Looks to be some issues with argument order, is docopt/argparse an option for next version

$ calyptos validate -e environment.yml 
Enter the SSH password for hosts in the deployment: ****
Usage: calyptos [OPTIONS] COMMAND [ARGS]...

Error: Missing option "-e" / "--environment".None

$ calyptos -e environment.yml validate

> > > Works as expected

**Comment by viglesiasce** [comment]
Hey @dmccue !

Thanks for the feedback. I agree the UX once I moved to using click was actually a regression. I am up for a PR that uses argparse again as long as we can keep the same subcommand type structure. 

For now I'm going to move the default options to the subcommands which will cause a bit more code in the calyptos file but gets us to the expected user experience.

**Comment by viglesiasce** [comment]
@dmccue ask and ye shall find! @bigschwan made these changes over in:
https://github.com/eucalyptus/calyptos/pull/23

**Comment by viglesiasce** [comment]
Closing now that #23 is in place.
