### ISSUE TITLE
Calyptos hangs when executed remotely (w/o tty?)

### ISSUE THREAD

**Issue by nephomaniac** [eucalyptus/calyptos#26]
Using commit: 73761e32628ddf81036e242b02dede94ae6c4179
(haven't checked with earlier commits but guessing this has been there for a while)

Looks like Calyptos hangs when executed remotely. 
Some "guesses" why:
- issue with fabric and tty?
- issue with flushing/not-flushing an fd like stdout, stderr (tried w/ and w/o --debug but doesnt matter)? 

Example:
ssh root@A.B.C.D 'calyptos --debug prepare -e calyptos/environment.yml -p foobar > calyptos.log 2>&1'
...yada...
...yada...

[10.111.1.100] Executing task 'push_deployment_data'
[10.111.5.58] Executing task 'push_deployment_data'
[10.111.1.178] Executing task 'push_deployment_data'
[10.111.1.107] Executing task 'push_deployment_data'
[10.111.5.56] Executing task 'push_deployment_data'
[10.111.1.99] Executing task 'push_deployment_data'
[10.111.5.3] Executing task 'push_deployment_data'
<hang>

In a local execution the output proceeds to something like the following, but never gets this far from a remote execution:
rsyncing deployment data...
rsyncing deployment data...
rsyncing deployment data...
rsyncing deployment data...
rsyncing deployment data...
rsyncing deployment data...
rsyncing deployment data...

**Comment by nephomaniac** [comment]
Tried with '-t' and it still froze prior to logging the rsync status. ssh -t root@a.b.c.d 'calyptos ....'

**Comment by viglesiasce** [comment]
Could be that at the end of the calyptos binary we need to call: fabric.network.disconnect_all
http://docs.fabfile.org/en/latest/api/core/network.html#fabric.network.disconnect_all

**Comment by nephomaniac** [comment]
Ok, nothing to do with tty or remote execution. 
Looks like calyptos is attempting to rsync from './' relative to where the command is executed from. For my remote case this ends up being in the login user's dir home dir. Maybe some recursive sync'ing going on as this was also where I was logging the output to. 
Looking into fixing this now to possibly only sync the the dirs required by the plugin, and possibly by a user specified path to it. In this case the local 'chef-repo/'. 
This ticket is probably a dup of:
https://github.com/eucalyptus/calyptos/issues/18

**Comment by viglesiasce** [comment]
Closing this in favor of #18
