### ISSUE TITLE
calyptos debug - behavior of ssh known_hosts file - fabric

### ISSUE THREAD

**Issue by dmccue** [eucalyptus/calyptos#31]
calyptos debug -e environment.yml 

```
Enter the SSH password for hosts in the deployment: 
```

[DEBUG STARTING      ] EucalyptusSosReports
[DEBUG STARTING      ] DebugClusterController
[DEBUG STARTING      ] CheckPorts
[DEBUG STARTING      ] FilePermissions
[DEBUG STARTING      ] DebugNodeController
[DEBUG STARTING      ] DebugCloudController

Fatal error: Host key for 10.104.10.44 did not match pre-existing key! Server's key was changed recently, or possible man-in-the-middle attack.

Underlying exception:
    ('10.104.10.44', <paramiko.rsakey.RSAKey object at 0x101983310>, <paramiko.rsakey.RSAKey object at 0x1018b77d0>)

Aborting.
[DEBUG RESULTS       ] Name: DebugCloudController Passed: 0 Failed: 0
[DEBUG RESULTS       ] Name: DebugNodeController Passed: 0 Failed: 0
[DEBUG RESULTS       ] Name: FilePermissions Passed: 0 Failed: 0
[DEBUG RESULTS       ] Name: CheckPorts Passed: 0 Failed: 0
[DEBUG RESULTS       ] Name: DebugClusterController Passed: 0 Failed: 0
[DEBUG RESULTS       ] Name: EucalyptusSosReports Passed: 0 Failed: 0

Suspect this is related to specifying ip addresses rather than hostnames.

**Comment by dmccue** [comment]
Workaround:
ssh-keygen -R 10.104.10.73
...
ssh-keygen -R [every IP specified in environment.yml]

Could calyptos be modified to either ignore known_hosts entries or alternatively run this shell command prior to executing fabric commands for debug?

Seems that validate, prepare, bootstrap, provision and uninstall use "-o StrictHostKeyChecking=no"

https://serverfault.com/questions/132970/can-i-automatically-add-a-new-host-to-known-hosts

**Comment by viglesiasce** [comment]
Hey @dmccue,

I talked a bit with @hspencer77 about this one and I felt like it was a disservice to ignore these by default since you could actually be in the middle of a MITM attack. 

What do you think of adding an --ignore-hosts flag that would ignore it for you but leaving it off by default?

**Comment by viglesiasce** [comment]
With the change I proposed we would need to change this as well: https://github.com/eucalyptus/calyptos/blob/master/calyptos/chefmanager.py#L36

Additionally we should probably unify the fabric env config across all plugins as part of this. Namely, debug and provisioning should not use different flags.

**Comment by dmccue** [comment]
--ignore-hosts would be excellent, more than happy just so long as there's an option as extracting out all mentioned IPs from the environment.yml file would be time-consuming
