### ISSUE TITLE
Calyptos: When deploying via internal network, NC connectivity is not restored

### ISSUE THREAD

**Issue by dmccue** [eucalyptus/calyptos#64]
Please find attached environment.yml

https://eucalyptus.atlassian.net/secure/attachment/25700/calyptos-1441686965.tgz
a logs/bootstrap.log
a logs/calyptos_commitid
a logs/environment.yml
a logs/prepare.log
a logs/provision.log
a logs/validate.log

During the install, the process hangs after 'service network restart' on all three NCs
Doesn't appear to re-assign static IP entries and defaults back to DHCP

``` bash

# Internal bridged interface
[root@odc-d-30 network-scripts]# cat /etc/sysconfig/network-scripts/ifcfg-em2
DEVICE=em2
TYPE=Ethernet
BRIDGE=br0
NOZEROCONF=true

#Internal bridged interface
[root@odc-d-30 network-scripts]# cat /etc/sysconfig/network-scripts/ifcfg-br0
DEVICE=br0
BOOTPROTO=dhcp       <=== Needs to be set to whatever was previously set in ifcfg-em2
NOZEROCONF=true
ONBOOT=yes
TYPE=Bridge
PERSISTENT_DHCLIENT=1

Missing lines in ifcfg-br0:
BOOTPROTO=none
IPADDR=10.105.1.209
NETMASK=255.255.0.0
DNS1=10.1.1.254
DNS2=8.8.8.8
PERSISTENT_DHCLIENT=yes
```

**Comment by viglesiasce** [comment]
@dmccue Ill take a look today. Should be an easy fix in the eucalyptus-cookbook.

**Comment by viglesiasce** [comment]
@dmccue my bad I assumed you wanted DHCP there. 

This will take a bit more work on my end to figure out the right way to swap those interface files.

**Comment by viglesiasce** [comment]
@dmccue this should be fixed here:

https://github.com/eucalyptus/eucalyptus-cookbook/pull/204

Let me know how it goes.

**Comment by dmccue** [comment]
Verified fixed, Thanks!: https://eucalyptus.atlassian.net/secure/attachment/25611/calyptos-1441138161.tgz

``` bash
[root@odc-d-30 ~]# cat /etc/sysconfig/network-scripts/ifcfg-em2
DEVICE=em2
TYPE=Ethernet
BRIDGE=br0
NOZEROCONF=true
[root@odc-d-30 ~]# cat /etc/sysconfig/network-scripts/ifcfg-br0
DEVICE=br0
ONBOOT=yes
HWADDR=B8:AC:6F:94:EC:44
TYPE=Ethernet
BOOTPROTO=none
IPADDR=10.105.1.209
NETMASK=255.255.0.0
DNS1=10.1.1.254
DNS2=8.8.8.8
PERSISTENT_DHCLIENT=yes
TYPE=Bridge
```
