### ISSUE TITLE
Calyptos: Stack trace when setting objectstorage.providerclient to walrus

### ISSUE THREAD

**Issue by dmccue** [eucalyptus/calyptos#67]
```
[10.105.10.51] out: Ran source /root/eucarc && http_proxy="" //usr/sbin/euca-modify-property -p objectstorage.providerclient=walrus returned 1
[10.105.10.51] out: [2015-09-09T02:51:44-07:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

Logs:
https://eucalyptus.atlassian.net/secure/attachment/25708/calyptos-1441792304.tgz

**Comment by dmccue** [comment]
Think this could be related to the walrus server not being registered:

``` bash
[root@odc-f-09 ~]# empyrean-describe-services --region @localhost | grep 'walrus\|storage'
SERVICE  objectstorage         API_10.105.10.67  API_10.105.10.67.objectstorage   broken                                                                                                             
SERVICE  storage               az-01             az-01-sc-1                       broken                                                                                                             
SERVICE  walrusbackend         walrus            walrus-1                         broken
```

``` bash
[root@odc-f-09 ~]# nc -z 10.105.10.44 8779
Connection to 10.105.10.44 8779 port [tcp/*] succeeded!
```

**Comment by dmccue** [comment]
Retried with identical symptoms:
https://eucalyptus.atlassian.net/secure/attachment/25709/calyptos-1441800742.tgz

**Comment by viglesiasce** [comment]
This isnt related to the Walrus specifically. All java components are down right now. 

Is anything different about the networking in this setup? It looks like the Java components arent able to talk to the CLC because the bind addr is set on the 10.104.x.y network rather than 10.105.x.y:

```
[root@odc-f-09 ~]# cat /etc/eucalyptus/eucalyptus.conf | grep bind
CLOUD_OPTS=" --bind-addr=10.104.10.51"
[root@odc-f-09 ~]#
```

**Comment by viglesiasce** [comment]
I see the issue now. I had thought this PR was already merged:
https://github.com/eucalyptus/eucalyptus-cookbook/pull/201

This does the auto detection for the bind-interface. Ill get that merged ASAP.

**Comment by viglesiasce** [comment]
@dmccue Its merged now. Sorry for the oversight.

**Comment by dmccue** [comment]
Fixed, Thanks! - https://eucalyptus.atlassian.net/secure/attachment/25611/calyptos-1441138161.tgz

[root@odc-f-09 ~]# grep bind /etc/eucalyptus/eucalyptus.conf
CLOUD_OPTS=" --bind-addr=10.105.10.51"
